# Dependencias
FROM node:22-alpine3.19 AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

# Stage para compilar código
FROM node:22-alpine3.19 AS build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

RUN npm run build

# Stage separada para deps de producción
FROM node:22-alpine3.19 AS prod-deps


WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --only=production && npm cache clean --force

COPY --from=build /usr/src/app/prisma ./prisma

COPY --from=build /usr/src/app/prisma.config.ts ./prisma.config.ts


# RUN npx prisma migrate dev

# Imagen final
FROM node:22-alpine3.19 AS prod

WORKDIR /usr/src/app

# Copiar node_modules de producción (ya incluye Prisma Client generado)
COPY --from=prod-deps /usr/src/app/node_modules ./node_modules

# Copiar código compilado
COPY --from=build /usr/src/app/dist ./dist

# Copiar archivos de Prisma
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/prisma.config.ts ./prisma.config.ts

# Crear y preparar directorio de datos
RUN mkdir -p /usr/src/app/data && \
    chown -R node:node /usr/src/app && \
    chmod -R 755 /usr/src/app/data

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy || npx prisma db push && node dist/src/main.js"]